name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '8.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:

  build-win-x64-arm64:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - run: dotnet publish BBDown -r win-x64 -c Release -o artifact-x64

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_win-x64
          path: artifact-x64\BBDown.exe
